# https://github.com/nightcycle/occlusion-camera/blob/main/.github/workflows/release.yml

name: Release package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'version.txt'

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get version
        id: version
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const core = require('@actions/core')
            const fs = require('fs');
            const version = fs.readFileSync('${{ github.workspace }}/version.txt', 'utf8')
            core.setOutput('version', version);
            console.log(version)

      - name: Update files with new version
        id: update-files
        shell: bash
        run: |
          # read wally.toml file
          wallyTOMLContents=$(<wally.toml)

          # swap out version
          targetVersionLine=$(echo "$wallyTOMLContents" | grep -F "version = ")
          goalVersionLine="version = \"${{ steps.version.outputs.version }}\""
          wallyTOMLContents="${wallyTOMLContents/${targetVersionLine}/${goalVersionLine}}"

          # update wally.toml file
          echo "$wallyTOMLContents" > wally.toml

      - name: Commit files with new version
        id: commit-files
        run: |
          # Commit version update
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add --all

          # Check if there are any changes to commit
          if git diff-index --quiet HEAD; then
            echo "No changes to push"
          else
            git commit -m "Update to v${{ steps.version.outputs.version }}"
            git push -u origin "${{ github.head_ref }}" --force-with-lease || true

            echo "Committed changes"
          fi

      - name: Install aftman dependencies
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Publish to wally
        shell: bash
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
        run: |
          rm -rf packages testez.toml .github node_modules .vscode
          mkdir -p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish

      # Create GitHub release
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true